/// A type that represents a named SF Symbol.
///
/// All per-category symbol enums generated by `SFSymbolsGenerator` conform to this protocol,
/// as does ``AnySymbol`` for type-erased usage.
///
/// Because all conforming types are either `enum` (with a `String` raw value) or a simple
/// value-type struct, `Sendable` conformance is always safe.
public protocol SFSymbolProtocol: RawRepresentable, Sendable where RawValue == String {
    /// The raw SF Symbol name, e.g. `"arrow.up.circle.fill"`.
    var symbolName: String { get }

    /// The categories this symbol belongs to.
    var categories: [SFSymbolCategory] { get }
}

public extension SFSymbolProtocol {
    var symbolName: String { rawValue }
}

// MARK: - AnySymbol

/// A type-erased SF Symbol that can hold any symbol from any category.
///
/// Use ``AnySymbol`` when you need to store or pass symbols without committing
/// to a specific category enum. All per-category enums can be converted to
/// ``AnySymbol`` via ``AnySymbol/init(_:)``.
public struct AnySymbol: SFSymbolProtocol, Hashable {
    public let rawValue: String
    public let categories: [SFSymbolCategory]

    public init(rawValue: String, categories: [SFSymbolCategory] = []) {
        self.rawValue = rawValue
        self.categories = categories
    }

    /// Required by `RawRepresentable`. Categories default to empty for ad-hoc symbols.
    public init?(rawValue: String) {
        self.rawValue = rawValue
        self.categories = []
    }

    /// Wraps any ``SFSymbolProtocol`` conforming value as an ``AnySymbol``.
    public init<S: SFSymbolProtocol>(_ symbol: S) {
        self.rawValue = symbol.rawValue
        self.categories = symbol.categories
    }

    public static func == (lhs: AnySymbol, rhs: AnySymbol) -> Bool {
        lhs.rawValue == rhs.rawValue
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rawValue)
    }
}

// MARK: - SFSymbolCategory convenience

public extension SFSymbolCategory {
    /// All symbols belonging to this category, derived from the generated lookup table.
    var symbols: [AnySymbol] {
        AnySymbol.allSymbols.filter { $0.categories.contains(self) }
    }
}
